version: '3.3'

services:

  app:
    container_name: stop-analyzing-embed
    image: stop-analyzing-embed:latest
    build: 
        dockerfile: Dockerfile
        context: .
    ports:
      - "8080:8080"
    networks:
      - host
    
networks:
  host:
    driver: bridge
    driver_opts:
       com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 192.168.126.0/22